DROP TABLE IF EXISTS TravelData;
CREATE TABLE IF NOT EXISTS TravelData (
    recordType                varchar(255),
    formTypeCd                varchar(255),
    schedFormTypeCd           varchar(255),
    reportInfoIdent           bigint,
    receivedDt                date,
    infoOnlyFlag              varchar(255),
    filerIdent                varchar(255),
    filerTypeCd               varchar(255),
    filerName                 varchar(255),
    travelInfoId              bigint,
    parentType                varchar(255),
    parentId                  bigint,
    parentDt                  date,
    parentAmount              numeric(12,2),
    parentFullName            varchar(255),
    transportationTypeCd      varchar(255),
    transportationTypeDescr   varchar(255),
    departureCity             varchar(255),
    arrivalCity               varchar(255),
    departureDt               date,
    arrivalDt                 date,
    travelPurpose             varchar(255),
    travellerPersentTypeCd    varchar(255),
    travellerNameOrganization varchar(255),
    travellerNameLast         varchar(255),
    travellerNameSuffixCd     varchar(255),
    travellerNameFirst        varchar(255),
    travellerNamePrefixCd     varchar(255),
    travellerNameShort        varchar(255)
);
